<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="BookHotelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HotelInfo" Member="HotelInfos">
    <Type Name="HotelInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PricePerNight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AvailableRooms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoOfBookedRooms" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>